# Generated by Django 4.2.9 on 2024-02-01 09:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='SubmitTicket',
            fields=[
                ('ticket', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('used', models.BooleanField(default=False)),
                ('oauth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.oauth')),
            ],
        ),
        migrations.CreateModel(
            name='DiagReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_health', models.CharField(choices=[(1, 'GOOD'), (2, 'OVERHEAT'), (3, 'DEAD'), (4, 'OVER_VOLTAGE'), (5, 'UNSPECIFIED_FAILURE'), (6, 'COLD'), (7, 'UNKNOWN')], default='UNKNOWN', max_length=100)),
                ('available_memory', models.BigIntegerField(default=0)),
                ('total_memory', models.BigIntegerField(default=0)),
                ('device_model', models.CharField(blank=True, default='', max_length=512)),
                ('device_brand', models.CharField(blank=True, default='', max_length=512)),
                ('device_board', models.CharField(blank=True, default='', max_length=512)),
                ('device_hardware', models.CharField(blank=True, default='', max_length=512)),
                ('device_manufacturer', models.CharField(blank=True, default='', max_length=512)),
                ('device_product', models.CharField(blank=True, default='', max_length=512)),
                ('os_version', models.CharField(default='0', max_length=512)),
                ('total_internal_memory', models.BigIntegerField(default=0)),
                ('is_port_healthy', models.BooleanField(default=False)),
                ('image', models.URLField(null=True)),
                ('submitted', models.BooleanField(default=False)),
                ('camera_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_from_camera', to='diag_report.file')),
                ('mic_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_from_mic', to='diag_report.file')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='diag_report.submitticket')),
            ],
        ),
    ]
