# Generated by Django 4.2.9 on 2024-01-30 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitTicket',
            fields=[
                ('ticket', models.UUIDField(primary_key=True, serialize=False)),
                ('used', models.BooleanField(default=False)),
                ('oauth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth.oauth')),
            ],
        ),
        migrations.CreateModel(
            name='DiagReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diag_report.submitticket')),
            ],
        ),
    ]
