# Generated by Django 4.2.9 on 2024-02-01 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diag_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagreport',
            name='battery_health',
            field=models.CharField(choices=[(1, 'GOOD'), (2, 'OVERHEAT'), (3, 'DEAD'), (4, 'OVER_VOLTAGE'), (5, 'UNSPECIFIED_FAILURE'), (6, 'COLD'), (7, 'UNKNOWN')], default='7', max_length=100),
        ),
    ]
