# Generated by Django 4.2.9 on 2024-01-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diag_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagreport',
            name='os_version',
            field=models.IntegerField(default=0, max_length=128),
        ),
    ]
