# Generated by Django 4.2.9 on 2024-01-30 12:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('diag_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitticket',
            name='ticket',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
